const DEFAULT_RESOURCES = {
    articles: [
        {
            id: "article-1",
            title: "Hiểu biết về sức khỏe tâm lý",
            description: "Tìm hiểu các khái niệm cơ bản về sức khỏe tâm lý và tại sao nó quan trọng",
            icon: "📖",
            category: "Tâm lý",
        },
        {
            id: "article-2",
            title: "Quản lý stress hàng ngày",
            description: "Các chiến lược hiệu quả để quản lý và giảm bớt stress trong cuộc sống hàng ngày",
            icon: "📚",
            category: "Stress",
        },
        {
            id: "article-3",
            title: "Mất ngủ: Nguyên nhân và giải pháp",
            description: "Tìm hiểu về mất ngủ và các cách tự nhiên để cải thiện chất lượng giấc ngủ",
            icon: "🌙",
            category: "Giấc ngủ",
        },
        {
            id: "article-4",
            title: "Xây dựng lòng tự trọng",
            description: "Cách phát triển và duy trì lòng tự trọng tích cực",
            icon: "💪",
            category: "Tự trọng",
        },
        {
            id: "article-5",
            title: "Vượt qua lo âu xã hội",
            description: "Các bước thực tế giúp giảm bớt sự lo lắng trong giao tiếp hằng ngày",
            icon: "🗣️",
            category: "Lo âu",
        },
        {
            id: "article-6",
            title: "Thói quen ngủ lành mạnh",
            description: "Hướng dẫn xây dựng routine ngủ sâu và tỉnh táo hơn vào buổi sáng",
            icon: "🛌",
            category: "Giấc ngủ",
        },
        {
            id: "article-7",
            title: "Mindfulness cho người bận rộn",
            description: "Các bài tập chánh niệm ngắn nhưng hiệu quả để cân bằng cảm xúc",
            icon: "🕯️",
            category: "Mindfulness",
        },
        {
            id: "article-8",
            title: "Phục hồi sau burnout",
            description: "Chiến lược lấy lại năng lượng và đặt ranh giới lành mạnh trong công việc",
            icon: "🔥",
            category: "Burnout",
        },
        {
            id: "article-9",
            title: "Nhận diện và xử lý cảm xúc tiêu cực",
            description: "Kỹ thuật nhận diện cảm xúc và chuyển hóa chúng một cách lành mạnh",
            icon: "🎯",
            category: "Kỹ năng cảm xúc",
        },
        {
            id: "article-10",
            title: "Nuôi dưỡng mối quan hệ tích cực",
            description: "Lời khuyên xây dựng mối quan hệ hỗ trợ và lành mạnh",
            icon: "🤝",
            category: "Quan hệ",
        },
        {
            id: "article-11",
            title: "Ứng phó với mất mát",
            description: "Hướng dẫn nhẹ nhàng để đi qua nỗi buồn và chấp nhận tổn thất",
            icon: "🕊️",
            category: "Tổn thất",
        },
        {
            id: "article-12",
            title: "Cân bằng công việc và cuộc sống",
            description: "Những thói quen giúp bạn tránh kiệt sức và giữ năng lượng tích cực",
            icon: "⚖️",
            category: "Work-life",
        },
        {
            id: "article-13",
            title: "Tự chăm sóc bản thân cho người bận rộn",
            description: "Các hoạt động nhỏ trong ngày để chăm sóc sức khỏe tinh thần",
            icon: "🛀",
            category: "Self-care",
        },
        {
            id: "article-14",
            title: "Giải tỏa cảm xúc qua nghệ thuật",
            description: "Sử dụng hội họa, âm nhạc hay viết để giải phóng cảm xúc",
            icon: "🎨",
            category: "Creativity",
        },
        {
            id: "article-15",
            title: "Lộ trình rèn luyện sự kiên nhẫn",
            description: "Các bài tập tăng khả năng chịu đựng và bình tĩnh",
            icon: "🐢",
            category: "Mindfulness",
        },
        {
            id: "article-16",
            title: "Đặt mục tiêu tinh thần lành mạnh",
            description: "Cách đặt mục tiêu phù hợp và tránh cảm giác thất bại",
            icon: "🎯",
            category: "Phát triển cá nhân",
        },
        {
            id: "article-17",
            title: "Làm chủ phản ứng căng thẳng",
            description: "Tìm hiểu phản ứng fight-flight-freeze và cách điều chỉnh",
            icon: "🧠",
            category: "Stress",
        },
        {
            id: "article-18",
            title: "Chăm sóc tâm lý sau chia tay",
            description: "Lời khuyên giúp bạn chữa lành và mở lòng trở lại",
            icon: "💔",
            category: "Quan hệ",
        },
        {
            id: "article-19",
            title: "Tập trung hơn với kỹ thuật Pomodoro",
            description: "Ứng dụng Pomodoro để cải thiện hiệu suất và giảm stress",
            icon: "⏳",
            category: "Năng suất",
        },
        {
            id: "article-20",
            title: "Tự tin chia sẻ cảm xúc",
            description: "Hướng dẫn mở lòng chia sẻ với người thân và chuyên gia",
            icon: "💬",
            category: "Giao tiếp",
        },
    ],
    techniques: [
        {
            id: "technique-1",
            title: "Hít thở sâu 4-7-8",
            description: "Kỹ thuật hít thở giúp giảm bớt căng thẳng và lo lắng trong vòng vài phút",
            icon: "🫁",
            duration: "5 phút",
            difficulty: "easy",
        },
        {
            id: "technique-2",
            title: "Thiền tâm",
            description: "Hướng dẫn thiền cơ bản để tập trung và xây dựng bình tĩnh nội tâm",
            icon: "🧘",
            duration: "10-20 phút",
            difficulty: "medium",
        },
        {
            id: "technique-3",
            title: "Viết cảm xúc",
            description: "Viết ra những cảm xúc của bạn để xử lý và giải tỏa stress",
            icon: "✍️",
            duration: "15 phút",
            difficulty: "easy",
        },
        {
            id: "technique-4",
            title: "Quét cơ thể (Body Scan)",
            description: "Kỹ thuật thư giãn toàn thân bằng cách tập trung vào từng bộ phận cơ thể",
            icon: "💆",
            duration: "20 phút",
            difficulty: "medium",
        },
        {
            id: "technique-5",
            title: "Luyện tập thư giãn cơ",
            description: "Thay phiên căng và thư giãn các nhóm cơ để giảm bớt căng thẳng",
            icon: "🏋️",
            duration: "15 phút",
            difficulty: "easy",
        },
        {
            id: "technique-6",
            title: "Hình ảnh hóa tích cực",
            description: "Sử dụng tưởng tượng để tạo trạng thái tâm lý tích cực",
            icon: "🌈",
            duration: "10 phút",
            difficulty: "medium",
        },
        {
            id: "technique-7",
            title: "Journaling 3 điều biết ơn",
            description: "Ghi lại 3 điều bạn biết ơn mỗi tối để củng cố cảm xúc tích cực",
            icon: "📓",
            duration: "10 phút",
            difficulty: "easy",
        },
        {
            id: "technique-8",
            title: "Thiền đi bộ chậm",
            description: "Kết hợp vận động nhẹ và quan sát hơi thở trong từng bước",
            icon: "🚶",
            duration: "15 phút",
            difficulty: "easy",
        },
        {
            id: "technique-9",
            title: "Progressive Relaxation",
            description: "Căng và thả lỏng tuần tự từng nhóm cơ để giảm lo âu",
            icon: "🧴",
            duration: "12 phút",
            difficulty: "medium",
        },
        {
            id: "technique-10",
            title: "Box Breathing 4-4-4-4",
            description: "Giữ nhịp thở đều 4s để ổn định hệ thần kinh",
            icon: "📦",
            duration: "4 phút",
            difficulty: "easy",
        },
        {
            id: "technique-11",
            title: "Thiền âm thanh",
            description: "Tập trung lắng nghe âm thanh xung quanh để giải phóng suy nghĩ",
            icon: "🎧",
            duration: "8 phút",
            difficulty: "easy",
        },
        {
            id: "technique-12",
            title: "Thiền lòng từ bi",
            description: "Gửi lời chúc phúc tới bản thân và người khác để tăng sự kết nối",
            icon: "💖",
            duration: "12 phút",
            difficulty: "medium",
        },
        {
            id: "technique-13",
            title: "Bài tập đếm điều tích cực",
            description: "Liệt kê 5 điều tích cực đã xảy ra trong ngày để thay đổi góc nhìn",
            icon: "📝",
            duration: "7 phút",
            difficulty: "easy",
        },
        {
            id: "technique-14",
            title: "Thư giãn bằng mùi hương",
            description: "Sử dụng tinh dầu hoặc trà thảo mộc để tạo cảm giác thư thái",
            icon: "🌿",
            duration: "10 phút",
            difficulty: "easy",
        },
        {
            id: "technique-15",
            title: "5-4-3-2-1 Grounding",
            description: "Nhận biết 5 giác quan để kéo tâm trí về hiện tại",
            icon: "🖐️",
            duration: "6 phút",
            difficulty: "easy",
        },
        {
            id: "technique-16",
            title: "Stretching nhẹ nhàng",
            description: "Chuỗi động tác kéo giãn giúp giải phóng căng cứng cơ thể",
            icon: "🤸",
            duration: "10 phút",
            difficulty: "easy",
        },
        {
            id: "technique-17",
            title: "Nghe nhạc tập trung",
            description: "Bật list nhạc alpha waves để lấy lại sự tập trung và giảm lo âu",
            icon: "🎶",
            duration: "15 phút",
            difficulty: "easy",
        },
        {
            id: "technique-18",
            title: "Bài tập cảm ơn bản thân",
            description: "Đứng trước gương và nói lời cảm ơn tới chính mình",
            icon: "🪞",
            duration: "5 phút",
            difficulty: "easy",
        },
        {
            id: "technique-19",
            title: "Mindful Eating",
            description: "Ăn chậm, cảm nhận hương vị để kết nối lại với cơ thể",
            icon: "🥗",
            duration: "10 phút",
            difficulty: "easy",
        },
        {
            id: "technique-20",
            title: "Pomodoro kèm nghỉ thư giãn",
            description: "25 phút làm việc + 5 phút thiền hoặc duỗi người",
            icon: "⏱️",
            duration: "30 phút",
            difficulty: "medium",
        },
    ],
    resources: [
        {
            id: "resource-1",
            title: "Playlist âm nhạc thư giãn",
            description: "Các bài nhạc được chọn lọc giúp thư giãn và cải thiện tâm trạng",
            icon: "🎵",
            category: "Âm nhạc",
        },
        {
            id: "resource-2",
            title: "Video yoga cơ bản",
            description: "Hướng dẫn video yoga dễ theo dõi cho người mới bắt đầu",
            icon: "🧘‍♀️",
            category: "Video",
        },
        {
            id: "resource-3",
            title: "Ứng dụng thiền Mindfulness",
            description: "Ứng dụng di động giúp luyện tập thiền hằng ngày",
            icon: "📱",
            category: "Ứng dụng",
        },
        {
            id: "resource-4",
            title: "Cộng đồng hỗ trợ tâm lý",
            description: "Kết nối với những người khác đang trên con đường tương tự",
            icon: "👥",
            category: "Cộng đồng",
        },
        {
            id: "resource-5",
            title: "Liên hệ chuyên gia tâm lý",
            description: "Danh sách các chuyên gia tâm lý được xác thực nếu bạn cần tư vấn chuyên sâu",
            icon: "👨‍⚕️",
            category: "Chuyên gia",
        },
        {
            id: "resource-6",
            title: "Sách hay về sức khỏe tâm lý",
            description: "Các cuốn sách được khuyến nghị về sức khỏe tâm lý và phát triển bản thân",
            icon: "📕",
            category: "Sách",
        },
        {
            id: "resource-7",
            title: "Podcast Healing Journey",
            description: "Chuỗi podcast chia sẻ câu chuyện hồi phục cảm xúc thực tế",
            icon: "🎧",
            category: "Podcast",
        },
        {
            id: "resource-8",
            title: "Bài tập kéo giãn buổi sáng",
            description: "Video 10 phút giúp đánh thức cơ thể và giải phóng năng lượng tiêu cực",
            icon: "🌅",
            category: "Video",
        },
        {
            id: "resource-9",
            title: "Checklist chăm sóc bản thân",
            description: "Tài liệu PDF gợi ý các hoạt động chăm sóc bản thân mỗi ngày",
            icon: "📝",
            category: "Tài liệu",
        },
        {
            id: "resource-10",
            title: "Sleep Stories Playlist",
            description: "Những câu chuyện nhẹ nhàng giúp đưa bạn vào giấc ngủ sâu",
            icon: "🌙",
            category: "Âm nhạc",
        },
        {
            id: "resource-11",
            title: "Ứng dụng Breathwork",
            description: "App hướng dẫn các bài thở theo nhịp để giảm lo âu",
            icon: "💨",
            category: "Ứng dụng",
        },
        {
            id: "resource-12",
            title: "Ebook tự chữa lành",
            description: "Sách điện tử miễn phí về hành trình chữa lành cảm xúc",
            icon: "📘",
            category: "Sách",
        },
        {
            id: "resource-13",
            title: "Workshop online về Mindfulness",
            description: "Lớp học trực tuyến ngắn giúp thực hành chánh niệm hằng ngày",
            icon: "💻",
            category: "Workshop",
        },
        {
            id: "resource-14",
            title: "Nhật ký cảm xúc kỹ thuật số",
            description: "Template Notion để theo dõi cảm xúc và thói quen",
            icon: "🗂️",
            category: "Template",
        },
        {
            id: "resource-15",
            title: "Cộng đồng MindScape trên Discord",
            description: "Không gian chia sẻ câu chuyện và nhận hỗ trợ từ người đồng cảnh",
            icon: "💬",
            category: "Cộng đồng",
        },
        {
            id: "resource-16",
            title: "Bộ thẻ bài tự phản chiếu",
            description: "Bộ thẻ câu hỏi giúp bạn tự khám phá cảm xúc",
            icon: "🃏",
            category: "Tool",
        },
        {
            id: "resource-17",
            title: "Playlist nhạc tập trung",
            description: "Nhạc nền giúp bạn duy trì sự tập trung mà vẫn thư thái",
            icon: "🎼",
            category: "Âm nhạc",
        },
        {
            id: "resource-18",
            title: "Series video tâm lý học tích cực",
            description: "Video giải thích các khái niệm giúp nâng cao tinh thần",
            icon: "📺",
            category: "Video",
        },
        {
            id: "resource-19",
            title: "Ứng dụng gratitude tracker",
            description: "App nhắc bạn ghi lại điều biết ơn hằng ngày",
            icon: "🙏",
            category: "Ứng dụng",
        },
        {
            id: "resource-20",
            title: "Danh sách chuyên gia khu vực",
            description: "Liên hệ các chuyên gia trị liệu tại địa phương của bạn",
            icon: "📍",
            category: "Chuyên gia",
        },
    ],
};

export { DEFAULT_RESOURCES };
export default DEFAULT_RESOURCES;